name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/server:latest

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/server:latest
          push: true

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push

    steps:
      - name: Get new image and replace container
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            cd sky
            
            docker stop client_frontend
            
            docker rm client_frontend
            
            docker rmi -f $(docker images -aq)
            
            docker compose up -d
